"""ChunkKit's stable, framework-neutral public API."""

from ._version import __version__
from .context import ContextAssembler, ContextPacker
from .errors import (
    ChunkKitError,
    ConfigurationError,
    IncompleteAclError,
    MissingExtraError,
    PluginError,
    TokenBudgetError,
)
from .models import (
    SCHEMA_VERSION,
    Acl,
    AclResolution,
    Checkpoint,
    Chunk,
    ChunkEdge,
    ChunkGraph,
    Citation,
    ContextBundle,
    DeleteArtifact,
    DiscardedSpan,
    Document,
    DroppedChunk,
    Element,
    ElementKind,
    ExperimentSpec,
    Metric,
    ModelProfile,
    ModelTarget,
    PipelineSpec,
    Principal,
    RawArtifact,
    RunReport,
    ScoredChunk,
    SourceSpan,
    TokenBudget,
    UpsertArtifact,
    Visibility,
)
from .pipeline import ChunkingPipeline
from .plugins import PluginManager, PluginManifest
from .profiles import ModelProfileRegistry
from .research import (
    ContextualEnricher,
    MultiResolutionPipeline,
    PropositionChunker,
    SemanticChunker,
)

__all__ = [
    "SCHEMA_VERSION",
    "Acl",
    "AclResolution",
    "Checkpoint",
    "Chunk",
    "ChunkEdge",
    "ChunkGraph",
    "ChunkKitError",
    "ChunkingPipeline",
    "Citation",
    "ConfigurationError",
    "ContextAssembler",
    "ContextBundle",
    "ContextPacker",
    "ContextualEnricher",
    "DeleteArtifact",
    "DiscardedSpan",
    "Document",
    "DroppedChunk",
    "Element",
    "ElementKind",
    "ExperimentSpec",
    "IncompleteAclError",
    "Metric",
    "MissingExtraError",
    "ModelProfile",
    "ModelProfileRegistry",
    "ModelTarget",
    "MultiResolutionPipeline",
    "PipelineSpec",
    "PluginError",
    "PluginManager",
    "PluginManifest",
    "Principal",
    "PropositionChunker",
    "RawArtifact",
    "RunReport",
    "ScoredChunk",
    "SemanticChunker",
    "SourceSpan",
    "TokenBudget",
    "TokenBudgetError",
    "UpsertArtifact",
    "Visibility",
    "__version__",
]
